/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Order {
  'status' : string,
  'total' : number,
  'userId' : string,
  'orderId' : string,
  'timestamp' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'name' : string,
  'productId' : string,
  'quantity' : bigint,
  'price' : number,
}
export interface OrderItemInput {
  'name' : string,
  'productId' : string,
  'quantity' : bigint,
  'price' : number,
}
export interface PublicProfile {
  'avatarBlob' : [] | [ExternalBlob],
  'userId' : string,
  'createdAt' : bigint,
  'isAdmin' : boolean,
}
export interface UserProfile {
  'avatarBlob' : [] | [ExternalBlob],
  'userId' : string,
  'createdAt' : bigint,
  'isAdmin' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllOrders' : ActorMethod<
    [],
    { 'ok' : Array<Order> } |
      { 'err' : string }
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getOrCreateProfile' : ActorMethod<[], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [Array<OrderItemInput>],
    { 'ok' : Order } |
      { 'err' : string }
  >,
  'updateProfileAdmin' : ActorMethod<
    [boolean],
    { 'ok' : PublicProfile } |
      { 'err' : string }
  >,
  'updateProfileAvatar' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];